### ISSUE TITLE
Add  simple add_filter to API for consistency

### ISSUE THREAD

**Issue by szepeviktor** [widoz/wp-hooks#14]
```php
\Widoz\WpHooks\addAction()
\Widoz\WpHooks\addFilter()
```

...and maybe the *Later variants :)

**Comment by widoz** [comment]
Them exists but are named `Removable` see https://github.com/widoz/wp-hooks/blob/develop/inc/api.php#L65 and https://github.com/widoz/wp-hooks/blob/develop/inc/api.php#L129

**Comment by szepeviktor** [comment]
Thank you.
Could you add a minimal usage instruction in README including this info?
