### ISSUE TITLE
Introduce container

### ISSUE THREAD

**Issue by widoz** [widoz/wp-hooks#25]
Make the library services available outside of the module

**Comment by szepeviktor** [comment]
This seems very interesting.
Please see https://github.com/j-arens/container

**Comment by widoz** [comment]
I thought to add support for standards https://github.com/php-fig/container and https://github.com/container-interop/service-provider

A file which return an array 

```
return [
    'wp-hook-factory' => function(Container $container) {
         return new WpHookFactory();
    }
]
```

The implementation will be part of the application so we do not decide which one third party has to implements, we just rely on abstraction here.

Now that I'm think about this we do not need to add service provider since we do not bootstrap anything but give the ability to retrieve instances as a service.

**Comment by widoz** [comment]
I completely removed the Factories from the listeners collection.
