### ISSUE TITLE
Remove HookType, actions are just filters since WP_Hook has been implemented

### ISSUE THREAD

**Issue by widoz** [widoz/wp-hooks#8]

**Comment by szepeviktor** [comment]
😃

**Comment by widoz** [comment]
@szepeviktor could you kindly check the PR, I would like to have your opinion in the changes I made.

**Comment by szepeviktor** [comment]
@widoz I think you've removes all hook types:

![kép](https://user-images.githubusercontent.com/952007/68996096-cd8de800-0895-11ea-931d-45406669663a.png)

**Comment by widoz** [comment]
@szepeviktor yes, since now  `HookType` idea does not exists anymore the factories are just creating instances of Removable, NTimes and Single Dispatcher.
The hook type context was implemented because Wp make differencese between actions and filters but now we removed that difference so everything is a filter.
